version: '3'
services:
  db:
    image: postgres:15
    build: db
    environment:
      POSTGRES_USER: pgsqldev4
      POSTGRES_PASSWORD: enter
      POSTGRES_DB: Sentimental_Analysis
    volumes:
      - ~/pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"

  api:
    build:
      context: ./sentimental_analysis
      dockerfile: Dockerfile
    ports:
      - "1171:1171"
    environment:
      ENVIRONMENT: prod
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: Sentimental_Analysis
      POSTGRES_USER: pgsqldev4
      POSTGRES_PASSWORD: enter
    depends_on:
      - db
    restart: always

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "1172:1172"
    environment:
      ENVIRONMENT: prod
      API_URL: http://api:1171/sentiment
    depends_on:
      - api
    restart: always
